package com.redofmaple.mapper;

import com.redofmaple.entity.gen.MCity;
import com.redofmaple.entity.gen.MCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Sat Oct 21 16:21:25 CST 2017
     */
    int countByExample(MCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Sat Oct 21 16:21:25 CST 2017
     */
    int deleteByExample(MCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Sat Oct 21 16:21:25 CST 2017
     */
    int insert(MCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Sat Oct 21 16:21:25 CST 2017
     */
    int insertSelective(MCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Sat Oct 21 16:21:25 CST 2017
     */
    List<MCity> selectByExample(MCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Sat Oct 21 16:21:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") MCity record, @Param("example") MCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_city
     *
     * @mbggenerated Sat Oct 21 16:21:25 CST 2017
     */
    int updateByExample(@Param("record") MCity record, @Param("example") MCityExample example);
}