package com.redofmaple.mapper;

import com.redofmaple.entity.gen.MProvince;
import com.redofmaple.entity.gen.MProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_province
     *
     * @mbggenerated Fri Oct 20 13:13:48 CST 2017
     */
    int countByExample(MProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_province
     *
     * @mbggenerated Fri Oct 20 13:13:48 CST 2017
     */
    int deleteByExample(MProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_province
     *
     * @mbggenerated Fri Oct 20 13:13:48 CST 2017
     */
    int insert(MProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_province
     *
     * @mbggenerated Fri Oct 20 13:13:48 CST 2017
     */
    int insertSelective(MProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_province
     *
     * @mbggenerated Fri Oct 20 13:13:48 CST 2017
     */
    List<MProvince> selectByExample(MProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_province
     *
     * @mbggenerated Fri Oct 20 13:13:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") MProvince record, @Param("example") MProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_province
     *
     * @mbggenerated Fri Oct 20 13:13:48 CST 2017
     */
    int updateByExample(@Param("record") MProvince record, @Param("example") MProvinceExample example);
}